import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import LandingPageWrapper from './LandingPageWrapper';
import StoreProvider from '@/redux/redux';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app'
};

export default function RootLayout({
	children
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body>
				<StoreProvider>
					<LandingPageWrapper>{children}</LandingPageWrapper>
				</StoreProvider>
			</body>
		</html>
	);
}
